### PR TITLE
Minimal run-context-mananger

### PR DESCRIPTION
**Pull request by christian-monch**
This PR is a minimized version of PR #484, that concentrates on the run-context-manager and the batch-context-manager and their application only.

I will close #484 for now in favor of this PR

TODO:

- [x] figure out https://github.com/datalad/datalad-next/issues/529#issuecomment-1784757155

### CODE REVIEW

**Comment by mih** [comment]
Thanks! This seems to be a sensible step!

Can we identify a concrete objective for this PR, so it can be reviewed adequately?

Would it be fair to say:

> This aims to make any *direct* use of any `Runner` class obsolete, in favor of a context-manager based pattern for (concurrent) subprocess execution.

Would that fit?

**Review by mih — CHANGES_REQUESTED** [review]
I went through the changes with the mindset of the objective being to take away needless flexibility of subprocess execution and to establish a context-manager-based pattern.

`ThreadedRunner` is not only a single private import: nice!

I think that `runners/batch.py` and `runners/tests/test_batch.py` should not be part of this PR. This is self-contained and tested code, but it is not used. Even if we have plans for adoption (later), this just adds weight to this PR and makes it less clear what this change is about IMHO.

**Comment by christian-monch** [comment]
> Thanks! This seems to be a sensible step!
> 
> Can we identify a concrete objective for this PR, so it can be reviewed adequately?
> 
> Would it be fair to say:
> 
> > This aims to make any _direct_ use of any `Runner` class obsolete, in favor of a context-manager based pattern for (concurrent) subprocess execution.
> 
> Would that fit?

Yes

> Edit: I will review based on the assumption that the answer is "yes"

👍🏻 
 
> FTR: It would be good to have PRs from forks to avoid running all CI twice.

Yeah, sorry. I messed up the upstream location on this one. Will take better care next time

**Comment by christian-monch** [comment]
> I went through the changes with the mindset of the objective being to take away needless flexibility of subprocess execution and to establish a context-manager-based pattern.
> 
> `ThreadedRunner` is not only a single private import: nice!
> 
> I think that `runners/batch.py` and `runners/tests/test_batch.py` should not be part of this PR. This is self-contained and tested code, but it is not used. Even if we have plans for adoption (later), this just adds weight to this PR and makes it less clear what this change is about IMHO.

I see your point. Will take it out into its own PR.

**Comment by christian-monch** [comment]
> [...]
> I think that `runners/batch.py` and `runners/tests/test_batch.py` should not be part of this PR. This is self-contained and tested code, but it is not used. Even if we have plans for adoption (later), this just adds weight to this PR and makes it less clear what this change is about IMHO.

Done

**Comment by christian-monch** [comment]
Marking this as "Ready for review". Remaing appveyor-errors are related to:

- `test_create_sibling_ghlike.py::test_gogs`
- `test_create_sibling_gogs.py::test_gogs`
-

**Comment by mih** [comment]
With #538 merged, we are betting on a new horse for subprocess execution. I believe this PR can be closed and/or reposted in  rejuvenated form.

**Pull request closed without merging**
