### PR TITLE
Add tests for progress report on size-less http downloads

### PR DESCRIPTION
**Pull request by christian-monch**
This PR adds a test to verify that http-download reports progress if no content-length is provided in the http-result headers. In addition the comments w.r.t. to download size calculation are updated to reflect the code.

This is a small add-on to #365 (which was already merged)

### CODE REVIEW

**Comment by mih** [comment]
This has been in draft mode for a long time. I know see that a review was requested (missed that due to the draft mode, sorry). I am closing this PR for now as part of a cleanup. Feel free to reopen when the conflicts are removed. Sorry for the hassle.

**Comment by christian-monch** [comment]
Conflicts removed and reopened

**Review by mih — APPROVED** [review]
LGTM, thx! Before merging, this needs a changelog, because it is not just adding a test.

**Comment by mih** [comment]
Sorry, no, only comments are adjusted.

**Pull request merged**
