### PR TITLE
Add missing and fix wrong docstrings for HTTP/WebDAV server related fixtures

### LINKED ISSUE #444: Small issues with docstrings of HTTP/WebDAV server related fixtures
"No fix without an issue", thus a quick issue description before I PR:

There are a few inconsistencies in the docstrings of the following fixtures:
image

(the first's docstring is missing, the highlighted line is wrong). Similarly, ``webdav_credential`` yet lacks a docstring.
image

### PR DESCRIPTION
**Pull request by adswa**
I noticed a few missing docstrings (``http_credential``, ``webdav_credential``), typos, and copy-paste errors (``http_server``) in the docstrings of these fixtures. Here is a quick fix.
Fixes #444

### CODE REVIEW

**Comment by adswa** [comment]
As these are only docstring changes, I've cancelled the Appveyor and CrippledFS runs.

**Review by christian-monch — APPROVED** [review]
Nice, thanks

**Comment by adswa** [comment]
thanks for the review, @christian-monch

**Review by mih — APPROVED** [review]
Thx!

**Pull request merged**
