### PR TITLE
Add the class `ZipArchiveOperations`, which implements archive operations on zip-files

### PR DESCRIPTION
**Pull request by christian-monch**
This PR adds `ZipArchiveOperations`, a class that implements `ArchiveOperations` for zip files. It makes use of
`datalad_next.iter_collections.zipfile.iter_zip` to implement iteration.

The PR includes tests. The test code comes with a new pytest-fixture called `sample_zip`, which creates a sample zip-file with known content, much like the `sample_tar_xz`-fixture.

Remark: while working on this PR, I came across a type-annotation issue #406. I will create a PR to solve #406 later

### CODE REVIEW

**Review by mih — COMMENTED** [review]
Thanks for this PR. It motivated me to implement https://github.com/datalad/datalad-next/pull/415 which addresses a number of insufficiencies  that became apparent while reviewing this PR. Please have a look re documentation and flexibility re archive item identifiers. I think it would make sense to align zip and tar support in this regard.

**Review by mih — CHANGES_REQUESTED** [review]
I believe we sorted out how this is supposed to be in various other PRs. I think mostly the item identifier flexibility needs to be aligned (allow for `PurePosixPath`) still.

**Comment by christian-monch** [comment]
Here is the plan:

- [ } Adapt existing tararchive operations to `TarfileItem.name`-typ, i.e. to `PurePosixPath`. (PR #426 )
- [ ] Align this PR with the changes from PR #426.
- [ ] Create a new PR to consolidate testing code, e.g. remove duplication

**Comment by christian-monch** [comment]
The zip file format introduces another naming-related quirk. Directory names in zip-files end with "/". All driectory-items (and file-items) that are yielded by `iter_zip` and by `ZipArchiveOperations.__iter__`, i.e. `ZipFileItem`-instances, have a `name`-property with type `PurePosixPath`. `PurePosixPath` does not distinguish between a path referring to a directory and a path referring to a file. It therefore also cannot be used to transparently do the "right thing". PR #430 introduces `ZipFileDirPath` to fix that.

**Comment by christian-monch** [comment]
FMPOV this is ready to go

**Comment by mih** [comment]
Looks like this PR is not longer up-to-speed with the other developments that happened since it was posted.

```
FAILED ../archive_operations/tests/test_zipfile.py::test_ziparchive_iterator - AssertionError: assert 'test-archive//' in ZipArchiveOperations(/home/appveyor/DLTMP/pytest-of-appveyor/pytest-0/zipfile0/sample.zip, cfg=None)
```

**Comment by mih** [comment]
Started working on an update

**Comment by mih** [comment]
Replaced by #578

**Pull request closed without merging**
