### PR TITLE
Rough sketch of an archivist annex remote

### PR DESCRIPTION
**Pull request by mih**
This sits on top of #215 

It would be a replacement for the implementation of the
`datalad-archives` remote. In addition to its predecessor,
it would support sparse/partial access to remote archives,
avoiding the 200% storage overhead, and the requirement to
unconditionally download full archives.

Ultimately this will address #185

Related issues:

- datalad/datalad#7121 (archives would no
  longer be fully extracted, and need no removal, unless configured)
- datalad/datalad#3270 (uses UrlOperations
  framework with standard progress reporting)
- datalad/datalad#373 (partial access to
  remote archives would be supported for all FSSPEC-supported
  archive types and access protocols)

### CODE REVIEW

**Comment by adswa** [comment]
I have merged the main branch into this PR to revive it, but one of the archivists tests now started to fail. This is what I'm seeing both in the CI as well as locally:

 ```
 E           datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex addurl --file testfile 'dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip' -c annex.dotfiles=true' failed with exitcode 1 under /crippledfs/pytest-of-runner/pytest-0/test_archivist_urlkey0 [out: 'addurl dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip (from archivist) (to testfile) 
 ```
 
 I'm not familiar with this implementation, but on first sight it looks like URL mangling is wrong. It tries ``https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip``, but I think that it should be two additional zeroes at the end of the zenodo record ID, and a # sign instead of a dash:
 
 
 ```diff
- https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
+ https://zenodo.org/record/6833100#3e2205a677322cba2b5616276b9d6824%23path=datalad-datalad-next-9b9c70a%2F.gitattributes&atype=zip'
```

**Comment by adswa** [comment]
I can confirm that this failure also occurs on the commit before I merged ``main``. I have also seen it happen with two different git-annex versions. 
It seems that it constructs the ``dl+archive`` URL out of the URL key, but the URL key has a butchered up record id:

```
ds.repo.call_annex([
        'addurl',
        '--file', 'testfile',
        f'dl+archive:{res["key"]}#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip',
    ])
(Pdb) p res
{'command': 'addurl', 'error-messages': [], 'file': '/tmp/pytest-of-adina/pytest-10/test_archivist_urlkey0/.archive/zenodo.zip', 'input': ['https://zenodo.org/record/6833100/files/datalad/datalad-next-0.4.1.zip'], 'key': 'URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824', 'note': 'to /tmp/pytest-of-adina/pytest-10/test_archivist_urlkey0/.archive/zenodo.zip', 'success': True}

```    

Here is a debug log from the special remote:
```console
(next) adina@muninn in /tmp/pytest-of-adina/pytest-10/test_archivist_urlkey0 on git:dl-test-branch+
❱ git annex -v -d addurl --file testfile 'dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip'

[2023-05-02 14:18:15.887291151] (Utility.Process) process [179615] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","git-annex"]
[2023-05-02 14:18:15.891040134] (Utility.Process) process [179615] done ExitSuccess
[2023-05-02 14:18:15.891710238] (Utility.Process) process [179616] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2023-05-02 14:18:15.894089956] (Utility.Process) process [179616] done ExitSuccess
[2023-05-02 14:18:15.894831317] (Utility.Process) process [179617] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..734af4c8c7c4eb9034cde9206b71301691c425da","--pretty=%H","-n1"]
[2023-05-02 14:18:15.897341918] (Utility.Process) process [179617] done ExitSuccess
[2023-05-02 14:18:15.898355098] (Utility.Process) process [179618] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2023-05-02 14:18:15.908853751] (Utility.Process) process [179619] chat: /home/adina/env/next/bin/git-annex-remote-archivist []
[2023-05-02 14:18:16.119573584] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> VERSION 1
[2023-05-02 14:18:16.119654856] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- EXTENSIONS INFO GETGITREMOTENAME ASYNC
[2023-05-02 14:18:16.119930314] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> EXTENSIONS
[2023-05-02 14:18:16.119972082] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- PREPARE
[2023-05-02 14:18:16.120172903] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> GETGITDIR
[2023-05-02 14:18:16.120212252] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- VALUE .git
[2023-05-02 14:18:16.136912639] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> GETGITREMOTENAME
[2023-05-02 14:18:16.137180335] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- VALUE archivist
[2023-05-02 14:18:16.137738555] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> DEBUG FSSPEC support disabled, dependency not available
[2023-05-02 14:18:16.137770185] (Remote.External) FSSPEC support disabled, dependency not available
[2023-05-02 14:18:16.13780819] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> PREPARE-SUCCESS
[2023-05-02 14:18:16.137846887] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- CLAIMURL dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:18:16.138076866] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> CLAIMURL-SUCCESS
[2023-05-02 14:18:16.138142486] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- CHECKURL dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:18:16.138304385] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> CHECKURL-CONTENTS UNKNOWN
addurl dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip (from archivist) (to testfile) [2023-05-02 14:18:16.138602286] (Utility.Process) process [179666] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","symbolic-ref","-q","HEAD"]
[2023-05-02 14:18:16.140062871] (Utility.Process) process [179666] done ExitSuccess
[2023-05-02 14:18:16.14051115] (Utility.Process) process [179667] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","refs/heads/dl-test-branch"]
[2023-05-02 14:18:16.141660579] (Utility.Process) process [179667] done ExitSuccess
[2023-05-02 14:18:16.141976224] (Utility.Process) process [179668] chat: git ["--git-dir=.git","--work-tree=.","-c","annex.debug=true","check-ignore","-z","--stdin","--verbose","--non-matching"]

[2023-05-02 14:18:16.143696448] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- TRANSFER RETRIEVE URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7 .git/annex/tmp/URL--dl,43archive&cURL--https&c%%zenod-303fa1dd3bdc9cd387174abe436e5ac7
[2023-05-02 14:18:16.14392368] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> GETURLS URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7 dl+archive:
[2023-05-02 14:18:16.14454937] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- VALUE dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:18:16.144597983] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- VALUE 
[2023-05-02 14:18:16.144741881] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> DEBUG Try retrieving 'URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7' from dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:18:16.144778296] (Remote.External) Try retrieving 'URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7' from dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:18:16.173600661] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> TRANSFER-FAILURE RETRIEVE URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7 Could not obtain 'URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7' from any URL

  Could not obtain 'URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7' from any URL
failed
[2023-05-02 14:18:16.21170819] (Utility.Process) process [179619] done ExitSuccess
[2023-05-02 14:18:16.212193237] (Utility.Process) process [179618] done ExitSuccess
[2023-05-02 14:18:16.212570517] (Utility.Process) process [179668] done ExitFailure 1
```

**Comment by adswa** [comment]
I solved the issue locally: I was missing fsspec. However, it was just a tiny debug output line that pointed me to it, and it is not obvious at any other level:

```
(next) adina@muninn in /tmp/pytest-of-adina/pytest-10/test_archivist_urlkey0 on git:dl-test-branch+
❱ pip install fsspec
Collecting fsspec
  Downloading fsspec-2023.4.0-py3-none-any.whl (153 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.0/154.0 kB 1.2 MB/s eta 0:00:00
Installing collected packages: fsspec
Successfully installed fsspec-2023.4.0
(next) adina@muninn in /tmp/pytest-of-adina/pytest-10/test_archivist_urlkey0 on git:dl-test-branch+
❱ git annex -v -d addurl --file testfile 'dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip'

[2023-05-02 14:25:26.244359255] (Utility.Process) process [179985] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","git-annex"]
[2023-05-02 14:25:26.246729501] (Utility.Process) process [179985] done ExitSuccess
[2023-05-02 14:25:26.247432787] (Utility.Process) process [179986] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2023-05-02 14:25:26.24953673] (Utility.Process) process [179986] done ExitSuccess
[2023-05-02 14:25:26.250241456] (Utility.Process) process [179987] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..9ba1c0c9248455b3681102e79da9ecb4eed401db","--pretty=%H","-n1"]
[2023-05-02 14:25:26.252661933] (Utility.Process) process [179987] done ExitSuccess
[2023-05-02 14:25:26.254147441] (Utility.Process) process [179988] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2023-05-02 14:25:26.267604324] (Utility.Process) process [179989] chat: /home/adina/env/next/bin/git-annex-remote-archivist []
[2023-05-02 14:25:26.497935686] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> VERSION 1
[2023-05-02 14:25:26.498033651] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- EXTENSIONS INFO GETGITREMOTENAME ASYNC
[2023-05-02 14:25:26.498204477] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> EXTENSIONS
[2023-05-02 14:25:26.498257162] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- PREPARE
[2023-05-02 14:25:26.498363728] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> GETGITDIR
[2023-05-02 14:25:26.498403654] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- VALUE .git
[2023-05-02 14:25:26.514578385] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> GETGITREMOTENAME
[2023-05-02 14:25:26.514904718] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- VALUE archivist
[2023-05-02 14:25:26.529904115] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> PREPARE-SUCCESS
[2023-05-02 14:25:26.529988099] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- CLAIMURL dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:25:26.530163158] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> CLAIMURL-SUCCESS
[2023-05-02 14:25:26.530236463] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- CHECKURL dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:25:26.530404289] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> CHECKURL-CONTENTS UNKNOWN
addurl dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip (from archivist) (to testfile) [2023-05-02 14:25:26.530879404] (Utility.Process) process [180036] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","symbolic-ref","-q","HEAD"]
[2023-05-02 14:25:26.532355914] (Utility.Process) process [180036] done ExitSuccess
[2023-05-02 14:25:26.532776854] (Utility.Process) process [180037] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","refs/heads/dl-test-branch"]
[2023-05-02 14:25:26.534222543] (Utility.Process) process [180037] done ExitSuccess
[2023-05-02 14:25:26.534817544] (Utility.Process) process [180038] chat: git ["--git-dir=.git","--work-tree=.","-c","annex.debug=true","check-ignore","-z","--stdin","--verbose","--non-matching"]

[2023-05-02 14:25:26.537131923] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- TRANSFER RETRIEVE URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7 .git/annex/tmp/URL--dl,43archive&cURL--https&c%%zenod-303fa1dd3bdc9cd387174abe436e5ac7
[2023-05-02 14:25:26.537392481] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> GETURLS URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7 dl+archive:
[2023-05-02 14:25:26.538098557] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- VALUE dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:25:26.538150485] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] <-- VALUE 
[2023-05-02 14:25:26.5382544] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> DEBUG Try retrieving 'URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7' from dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:25:26.538293878] (Remote.External) Try retrieving 'URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7' from dl+archive:URL--https://zenodo.org/record/68331-3e2205a677322cba2b5616276b9d6824#path=datalad-datalad-next-9b9c70a/.gitattributes&atype=zip
[2023-05-02 14:25:26.564627301] (Annex.ExternalAddonProcess) /home/adina/env/next/bin/git-annex-remote-archivist[1] --> TRANSFER-SUCCESS RETRIEVE URL--dl,43archive:URL--https://zenod-303fa1dd3bdc9cd387174abe436e5ac7
[2023-05-02 14:25:26.565247278] (Utility.Process) process [180060] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","check-attr","-z","--stdin","annex.backend","annex.largefiles","annex.numcopies","annex.mincopies","--"]
[2023-05-02 14:25:26.568032891] (Annex.Branch) read 80d/5e0/MD5E-s38--4be73eb2ee4b7a67f79fe0f5a26c0c7b.log.web
[2023-05-02 14:25:26.568515561] (Annex.Branch) set 80d/5e0/MD5E-s38--4be73eb2ee4b7a67f79fe0f5a26c0c7b.log.web
[2023-05-02 14:25:26.568606556] (Annex.Branch) read 80d/5e0/MD5E-s38--4be73eb2ee4b7a67f79fe0f5a26c0c7b.log
[2023-05-02 14:25:26.56894653] (Annex.Branch) set 80d/5e0/MD5E-s38--4be73eb2ee4b7a67f79fe0f5a26c0c7b.log
[2023-05-02 14:25:26.569520982] (Utility.Process) process [180061] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","hash-object","-w","--stdin-paths","--no-filters"]
[2023-05-02 14:25:26.57114552] (Annex.Perms) freezing content .git/annex/objects/Q0/Xx/MD5E-s38--4be73eb2ee4b7a67f79fe0f5a26c0c7b/MD5E-s38--4be73eb2ee4b7a67f79fe0f5a26c0c7b
[2023-05-02 14:25:26.571990087] (Utility.Process) process [180062] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","write-tree"]
[2023-05-02 14:25:26.573333042] (Utility.Process) process [180062] done ExitSuccess
[2023-05-02 14:25:26.57371963] (Utility.Process) process [180064] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/annex/last-index"]
[2023-05-02 14:25:26.575082286] (Utility.Process) process [180064] done ExitSuccess
[2023-05-02 14:25:26.575336087] (Annex.Perms) freezing content directory .git/annex/objects/Q0/Xx/MD5E-s38--4be73eb2ee4b7a67f79fe0f5a26c0c7b
[2023-05-02 14:25:26.575442795] (Annex.Branch) read 80d/5e0/MD5E-s38--4be73eb2ee4b7a67f79fe0f5a26c0c7b.log
[2023-05-02 14:25:26.575728771] (Annex.Branch) set 80d/5e0/MD5E-s38--4be73eb2ee4b7a67f79fe0f5a26c0c7b.log
ok
(recording state in git...)
[2023-05-02 14:25:26.576115904] (Utility.Process) process [180065] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-index","-z","--index-info"]
[2023-05-02 14:25:26.577413527] (Utility.Process) process [180065] done ExitSuccess
[2023-05-02 14:25:26.578406209] (Utility.Process) process [180066] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-index","-z","--index-info"]
[2023-05-02 14:25:26.579935857] (Utility.Process) process [180066] done ExitSuccess
[2023-05-02 14:25:26.580533411] (Utility.Process) process [180067] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2023-05-02 14:25:26.58182535] (Utility.Process) process [180067] done ExitSuccess
[2023-05-02 14:25:26.582338803] (Utility.Process) process [180068] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","write-tree"]
[2023-05-02 14:25:26.584269309] (Utility.Process) process [180068] done ExitSuccess
[2023-05-02 14:25:26.584740475] (Utility.Process) process [180069] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","commit-tree","b3c841c413cdef068cf50b180846fd8aa1d17b73","--no-gpg-sign","-p","refs/heads/git-annex"]
[2023-05-02 14:25:26.586284877] (Utility.Process) process [180069] done ExitSuccess
[2023-05-02 14:25:26.586794489] (Utility.Process) process [180070] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-ref","refs/heads/git-annex","92c97451375fa44c8bd6b9cd1c59cb8e24d21716"]
[2023-05-02 14:25:26.588363249] (Utility.Process) process [180070] done ExitSuccess
[2023-05-02 14:25:26.637276746] (Utility.Process) process [179989] done ExitSuccess
[2023-05-02 14:25:26.637816146] (Utility.Process) process [179988] done ExitSuccess
[2023-05-02 14:25:26.638155256] (Utility.Process) process [180060] done ExitSuccess
[2023-05-02 14:25:26.638498958] (Utility.Process) process [180061] done ExitSuccess
[2023-05-02 14:25:26.63881631] (Utility.Process) process [180038] done ExitFailure 1
```

It might need a dependency on fsspec and better error communication or a check about this

**Comment by mih** [comment]
The dependency issue is a TODO in https://github.com/datalad/datalad-next/pull/215 -- which is the basis for this PR and also in draft mode.

**Comment by adswa** [comment]
The current failure contains an internal fsspec Attribute error. This has very recently (yesterday) been fixed: https://github.com/fsspec/filesystem_spec/pull/1253

**Comment by mih** [comment]
With #380 now being functional, we can close this chapter. FSSPEC can be introduced at a future point in time.

**Pull request closed without merging**
